apiVersion: v1
kind: Service
metadata:
  name: my-lb
  labels:
    app: my-api
  namespace: web-app
spec:
  type: LoadBalancer
  ports:
  - port: 5000 # Port on which the service is running
    targetPort: 5000 # Port on which the container is running
  selector:
    app: my-api